# Generated by Django 5.2.6 on 2025-10-02 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('picture', models.URLField(default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRacVJgp_9zRgc2L-q85jH0Llc9G2oQaL47ZA&s')),
                ('cuisine', models.CharField(max_length=100)),
                ('ratting', models.FloatField()),
            ],
        ),
    ]
