# Generated by Django 5.2.6 on 2025-10-05 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_restaurant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='ratting',
            new_name='rating',
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='picture',
            field=models.URLField(default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRacVJgp_9zRgc2L-q85jH0Llc9G2oQaL47ZA&s', max_length=500),
        ),
    ]
